[package]
name = "cn_5_effet_filtrage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
find_peaks = "0.1.5"
plotters = "0.3.5"
rustfft = "6.2.0"
